version: "3.7"
services:
  web:
    build: web
    restart: always
    ports:
      - 5000:5000
    environment:
      - DEBUG=${DEBUG}
    networks:
      - flask_network
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  flask_network:

volumes:
  postgres_data: